version: 2
jobs:
  build_amps:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout

      - restore_cache:
          key: mms-{{ checksum "mms-ent/pom.xml" }}

      - run: cd mms-ent && sh mvnw install -Pbuild

      - save_cache:
          paths:
            - ~/.m2
          key: mms-{{ checksum "mms-ent/pom.xml" }}

      - store_artifacts:
          path: mms-ent/repo-amp/target/mms-*.amp
          destination: /tmp/artifacts

      - store_artifacts:
          path: mms-ent/share-amp/target/mms-*.amp
          destination: /tmp/artifacts

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_amps
