version: 2
jobs:
  build_amps:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: cd mms-ent && sh mvnw install -Pbuild
      - store_artifacts:
          path: /tmp/artifacts
          destination: build

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_amps
