version: 2
jobs:
  build_amps:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout

      - run: cd mms-ent && sh mvnw install -Pbuild

      - store_artifacts:
          path: repo-amp/target/mms-*.amp

      - store_artifacts:
          path: share-amp/target/mms-*.amp

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_amps
