defaults: &defaults
  working_directory: ~/projects
  docker:
    - image: circleci/openjdk:8
    - image: circleci/postgres:9.6.2-alpine
      environment:
        POSTGRES_USER: mmsuser
        POSTGRES_DB: mms
    - image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
      environment:
        - discovery.type=single-node
        - http.host=127.0.0.1
        - transport.host=127.0.0.1
        - xpack.security.enabled=false
        - ES_JAVA_OPTS=-Xms750m -Xmx750m

version: 2
jobs:
  build_amps:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: mms-{{ checksum "mms-ent/pom.xml" }}

      - run:
          name: Get Postgresql Client
          command: sudo apt install postgresql-client

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

      - run:
          name: Initialize database
          command: psql -U mmsuser -h localhost -f mms-ent/repo-amp/src/resources/mms.sql mms

      - run:
          name: Initialize elasticsearch
          command: curl -d @mms-ent/repo-amp/src/resources/mapping_template.json -XPUT http://localhost:9200/_template/template

      - run:
          name: Run Maven Build
          command: cd mms-ent && sh mvnw install -Prun,robot-tests

      - save_cache:
          paths:
            - ~/.m2
          key: mms-{{ checksum "mms-ent/pom.xml" }}

      - run:
          name: Prepare Store Artifacts
          command: mkdir -p tmp/artifacts

      - store_artifacts:
          path: mms-ent/repo-amp/target/mms-amp-3.3.0-SNAPSHOT.amp
          destination: tmp/artifacts/mms-amp-3.3.0-SNAPSHOT.amp

      - store_artifacts:
          path: mms-ent/share-amp/target/mms-share-amp-3.3.0-SNAPSHOT.amp
          destination: tmp/artifacts/mms-share-amp-3.3.0-SNAPSHOT.amp

      - persist_to_workspace:
          root: mms-ent
          paths:
            - repo-amp/target
            - share-amp/target

  deploy_snapshot:
    <<: *defaults
    steps:
      - attach_workspace:
          at: mms-ent
      - run:
          name: Get jfrog
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Set Permissions
          command: sudo chmod +x jfrog
      - run:
          name: Configure jfrog
          command: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive false
      - run:
          name: Send mms-amp
          command: ./jfrog rt u 'mms-ent/repo-amp/target/*.amp' libs-snapshot-local/gov/nasa/jpl/mms/mms-amp/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true
      - run:
          name: Send mms-share-amp
          command: ./jfrog rt u 'mms-ent/share-amp/target/*.amp' libs-snapshot-local/gov/nasa/jpl/mms/mms-share-amp/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true

  deploy_release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: mms-ent
      - run:
          name: Get jfrog
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Set Permissions
          command: sudo chmod +x jfrog
      - run:
          name: Configure jfrog
          command: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive false
      - run:
          name: Send mms-amp
          command: ./jfrog rt u 'mms-ent/repo-amp/target/*.amp' libs-release-local/gov/nasa/jpl/mms/mms-amp/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true
      - run:
          name: Send mms-share-amp
          command: ./jfrog rt u 'mms-ent/share-amp/target/*.amp' libs-release-local/gov/nasa/jpl/mms/mms-share-amp/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true

workflows:
  version: 2
  build-deploy-snapshot:
    jobs:
      - build_amps
      - deploy_snapshot:
          requires:
            - build_amps
