defaults: &defaults
  working_directory: ~/projects
  docker:
    - image: circleci/openjdk:8

version: 2
jobs:
  build_amps:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: mms-{{ checksum "mms-ent/pom.xml" }}

      - run:
          name: Build mms
          command: cd mms-ent && sh mvnw install -Pbuild

      - save_cache:
          paths:
            - ~/.m2
          key: mms-{{ checksum "mms-ent/pom.xml" }}

      - store_artifacts:
          path: mms-ent/repo-amp/target/mms-amp-3.3.0-SNAPSHOT.amp
          destination: /tmp/

      - store_artifacts:
          path: mms-ent/share-amp/target/mms-share-amp-3.3.0-SNAPSHOT.amp
          destination: /tmp/

      - persist_to_workspace:
          root: /
          paths:
            - tmp

  deploy_amps:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Get jfrog
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Set permissions
          command: sudo chmod +x jfrog
      - run:
          name: Configure jfrog
          command: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive false
      - run:
          name: Send mms-amp
          command: ./jfrog rt u "mms-amp-3.3.0-SNAPSHOT.amp" mms-snapshots --build-name=mms-amp-3.3.0-SNAPSHOT --build-number=$CIRCLE_BUILD_NUM --flat=false
      - run:
          name: Send mms-share-amp
          command: ./jfrog rt u "mms-share-amp-3.3.0-SNAPSHOT.amp" mms-share-snapshots --build-name=mms-share-amp-3.3.0-SNAPSHOT --build-number=$CIRCLE_BUILD_NUM --flat=false

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_amps
      - deploy_amps:
          requires:
            - build_amps
