version: 2
jobs:
  build_amps:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout

      - restore_cache:
          key: mms-{{ checksum "mms-ent/pom.xml" }}

      - run: cd mms-ent && sh mvnw dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: mms-{{ checksum "mms-ent/pom.xml" }}

      - run: cd mms-ent && sh mvnw install -Pbuild

      - store_artifacts:
          path: repo-amp/target/mms-*.amp

      - store_artifacts:
          path: share-amp/target/mms-*.amp

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_amps
