defaults: &defaults
  working_directory: ~/projects
  docker:
    - image: circleci/openjdk:8

version: 2
jobs:
  build_amps:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: mms-{{ checksum "mms-ent/pom.xml" }}

      - run:
          name: Run Maven Build
          command: cd mms-ent && sh mvnw install -Pbuild && sh mvnw install -f repo-amp/target/generated-sources/swagger/java/pom.xml

      - save_cache:
          paths:
            - ~/.m2
          key: mms-{{ checksum "mms-ent/pom.xml" }}

      - run:
          name: Prepare Store Artifacts
          command: mkdir -p tmp/artifacts

      - store_artifacts:
          path: mms-ent/repo-amp/target

      - store_artifacts:
          path: mms-ent/share-amp/target

      - persist_to_workspace:
          root: mms-ent
          paths:
            - repo-amp/target
            - share-amp/target

  deploy_snapshot:
    <<: *defaults
    steps:
      - attach_workspace:
          at: mms-ent
      - run:
          name: Get jfrog
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Set Permissions
          command: sudo chmod +x jfrog
      - run:
          name: Configure jfrog
          command: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive false
      - run:
          name: Send mms-amp
          command: ./jfrog rt u 'mms-ent/repo-amp/target/*.amp' libs-snapshot-local/gov/nasa/jpl/mms/mms-amp/3.3.1-SNAPSHOT/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true
      - run:
          name: Send mms-share-amp
          command: ./jfrog rt u 'mms-ent/share-amp/target/*.amp' libs-snapshot-local/gov/nasa/jpl/mms/mms-share-amp/3.3.1-SNAPSHOT/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true
      - run:
          name: Send mms java client
          command: ./jfrog rt u 'mms-ent/repo-amp/target/mms-java-*.zip' libs-snapshot-local/gov/nasa/jpl/mms/mms-java-client/3.3.1-SNAPSHOT/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true
      - run:
          name: Send mms python client
          command: ./jfrog rt u 'mms-ent/repo-amp/target/mms-python-*.zip' libs-snapshot-local/gov/nasa/jpl/mms/mms-python-client/3.3.1-SNAPSHOT/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true
      - run:
          name: Send mms mathematica client
          command: ./jfrog rt u 'mms-ent/repo-amp/target/mms-mathematica-*.zip' libs-snapshot-local/gov/nasa/jpl/mms/mms-mathematica-client/3.3.1-SNAPSHOT/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true

  deploy_release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: mms-ent
      - run:
          name: Get jfrog
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Set Permissions
          command: sudo chmod +x jfrog
      - run:
          name: Configure jfrog
          command: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive false
      - run:
          name: Send mms-amp
          command: ./jfrog rt u 'mms-ent/repo-amp/target/*.amp' libs-release-local/gov/nasa/jpl/mms/mms-amp/3.3.1-SNAPSHOT/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true
      - run:
          name: Send mms-share-amp
          command: ./jfrog rt u 'mms-ent/share-amp/target/*.amp' libs-release-local/gov/nasa/jpl/mms/mms-share-amp/3.3.1-SNAPSHOT/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true
      - run:
          name: Send mms java client
          command: ./jfrog rt u 'mms-ent/repo-amp/target/mms-java-*.zip' libs-release-local/gov/nasa/jpl/mms/mms-java-client/3.3.1-SNAPSHOT/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true
      - run:
          name: Send mms python client
          command: ./jfrog rt u 'mms-ent/repo-amp/target/mms-python-*.zip' libs-release-local/gov/nasa/jpl/mms/mms-python-client/3.3.1-SNAPSHOT/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true
      - run:
          name: Send mms mathematica client
          command: ./jfrog rt u 'mms-ent/repo-amp/target/mms-mathematica-*.zip' libs-release-local/gov/nasa/jpl/mms/mms-mathematica-client/3.3.1-SNAPSHOT/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true

workflows:
  version: 2
  build-deploy-snapshot:
    jobs:
      - build_amps
      - deploy_snapshot:
          requires:
            - build_amps
